version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    image: sridhar76/vrs-dairy-backend:latest
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/dairy
    depends_on:
      - mongodb
    networks:
      - dairy-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: sridhar76/vrs-dairy-frontend:latest
    ports:
      - "80:80"
    networks:
      - dairy-network

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - dairy-network

networks:
  dairy-network:
    driver: bridge

volumes:
  mongo-data: