apiVersion: v1
kind: Service
metadata:
  name: vrs-dairy-service
spec:
  selector:
    app: vrs-dairy  
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8090
  type: LoadBalancer
  